# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import russian_fields.agency_type_esia
import russian_fields.gender
import russian_fields.inn
import russian_fields.kpp
import russian_fields.ogrn
import russian_fields.territory_code


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample2Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', russian_fields.inn.INNField(blank=True, null=True)),
                ('inn_person', russian_fields.inn.INNPersonField(blank=True, mode='person', null=True)),
                ('inn_business', russian_fields.inn.INNBusinessField(blank=True, mode='legal', null=True)),
                ('kpp', russian_fields.kpp.KPPField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sample2Model',
                'verbose_name_plural': 'Sample2Models',
            },
        ),
        migrations.CreateModel(
            name='Sample3Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ogrn', russian_fields.ogrn.OGRNField(blank=True, null=True)),
                ('ogrn_legal', russian_fields.ogrn.OGRNLegalField(blank=True, mode='legal', null=True)),
                ('ogrn_business', russian_fields.ogrn.OGRNBusinessField(blank=True, mode='business', null=True)),
            ],
            options={
                'verbose_name': 'Sample3Model',
                'verbose_name_plural': 'Sample3Models',
            },
        ),
        migrations.CreateModel(
            name='SampleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', russian_fields.gender.GENDERField(blank=True, null=True)),
                ('agency_type_esia', russian_fields.agency_type_esia.AgencyTypeESIA(blank=True, null=True)),
                ('territory_code', russian_fields.territory_code.TerritoryCodeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'SampleModel',
                'verbose_name_plural': 'SampleModels',
            },
        ),
    ]
