# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import russian_fields.gender


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SampleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', russian_fields.gender.GENDERField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'SampleModel',
                'verbose_name_plural': 'SampleModels',
            },
        ),
    ]
