# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 14:42
from __future__ import unicode_literals

from django.db import migrations
import russian_fields.agency_type_esia


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplemodel',
            name='agency_type_esia',
            field=russian_fields.agency_type_esia.AgencyTypeESIA(blank=True, null=True),
        ),
    ]
