# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 05:07
from __future__ import unicode_literals

from django.db import migrations, models
import russian_fields.okogu
import russian_fields.okopf
import russian_fields.snils


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample4Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('okogu', russian_fields.okogu.OKOGUField(blank=True, null=True)),
                ('okopf', russian_fields.okopf.OKOPFField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sample4Model',
                'verbose_name_plural': 'Sample4Models',
            },
        ),
        migrations.CreateModel(
            name='Sample5Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snils', russian_fields.snils.SNILSField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sample5Model',
                'verbose_name_plural': 'Sample5Models',
            },
        ),
    ]
