# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import russian_fields.inn


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_samplemodel_territory_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample2Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', russian_fields.inn.INNField(blank=True, null=True)),
                ('inn_person', russian_fields.inn.INNPersonField(blank=True, mode='person', null=True)),
                ('inn_business', russian_fields.inn.INNBusinessField(blank=True, mode='legal', null=True)),
            ],
            options={
                'verbose_name': 'Sample2Model',
                'verbose_name_plural': 'Sample2Models',
            },
        ),
    ]
