# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 08:31
from __future__ import unicode_literals

from django.db import migrations
import russian_fields.kpp


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_sample2model'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample2model',
            name='kpp',
            field=russian_fields.kpp.KPPField(blank=True, null=True),
        ),
    ]
